import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { FilterProvider } from "../context/filter_context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full flex flex-col justify-center items-center antialiased`}
      >
        <FilterProvider>
          <Header />
          <main className="max-w-[1920px] w-full  mx-auto px-[120px]" >
          {children}
          </main>
        </FilterProvider>
      </body>
    </html>
  );
}
